## About today's class

This week, we continue to look at big data tools that work synergistically for data analytics. These tools are meant for big-ish data, and leverage the Parquet file format. We can process TB-level data easily using these tools, and they can work well with AWS S3 storage. 

All our work will be done on AWS, so make sure you're set up following [Lab 3](/labs/03a-labs.qmd).

## Readings

No new readings for this week, but you should have completed the readings for last week (to be completed ***before this class***):

-   [DuckDB Up and Running](https://learning.oreilly.com/library/view/duckdb-up-and/9781098159689/) by Wei-Meng Lee (2025). Chapters 2, 4, 8. (Available via [O'Reilly Online Learning](https://go.oreilly.com/gwu-edu){target="_blank"} through the Gelman Library)

-   [Python Polars: The Definitive Guide](https://learning.oreilly.com/library/view/python-polars-the/9781098156077/){target="_blank"} by Jannsens & Nieuwdorp (2025). Chapter 5 (Available via [O'Reilly Online Learning](https://go.oreilly.com/gwu-edu){target="_blank"} through the Gelman Library)

## Slides

The slides for this week are available [online](/slides/05-slides.qmd). 

## Lab

This week the formal lab will explore 1 year of the NYC Taxi dataset using Parquet and Polars, showing the advantages of columnar formatting, smart partitioning and no-copy analytics. 

The Github Classroom link is [{{<var gh-classroom.lab05 >}}]({{< var gh-classroom.lab05 >}}) and is due {{< var due_dates.lab05 >}}

## Assignment

There are two assignments this week:

1. **Assignment 5**: This assignment will focus on using Polars and DuckDB for data analysis on Parquet datasets. The assignment will be released on Friday, February 13th, and will be due on Sunday, February 22rd.
2. **Project Milestone 1**: The first milestone for the final project will be due on Wednesday, February 21nd. This milestone will require you to submit a project proposal outlining your research question, data sources, and proposed analysis methods. The proposal should be approximately 1-2 pages in length and should demonstrate a clear understanding of the data and methods you plan to use for your final project. If you are not using the Reddit dataset, your proposal will also need to include a data acquisition plan detailing how you will obtain and prepare your dataset for analysis, and **this plan must be approved by the instructor before you proceed with your project**.

Information about the Reddit dataset is available [here](/project/reddit-s3-copy-instructions.md)